//
//  CuisineSeeds.swift
//  Appetite
//
//  Created by Adrian on 11/23/16.
//  Copyright © 2016 Kuguar. All rights reserved.
//

import Foundation
import RealmSwift

class CuisineSeeds {

  class func all() -> [(
    name: String,
    name_locale: String,
    info: String,
    locale: String,
    version: String,
    order: String,
    position: Int,
    isActive:Bool,
    isDeleted: Bool
    )]{

    var seeds:[(
      name: String,
      name_locale: String,
      info: String,
      locale: String,
      version: String,
      order: String,
      position: Int,
      isActive:Bool,
      isDeleted: Bool
      )] = []

    seeds.append(("Afghan",                         "Afghan",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("African",                        "African",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ainu",                           "Ainu",                           "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Akan",                           "Akan",                           "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Albanian",                       "Albanian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Algerian",                       "Algerian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("American",                       "American",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Americas",                       "Americas",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ancient Egyptian",               "Ancient Egyptian",               "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ancient Greek",                  "Ancient Greek",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ancient Israelite",              "Ancient Israelite",              "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ancient Roman",                  "Ancient Roman",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Andalusian",                     "Andalusian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Angolan",                        "Angolan",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Arab",                           "Arab",                           "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Arabian",                        "Arabian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Argentine",                      "Argentine",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Armenian",                       "Armenian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Asian",                          "Asian",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Assyrian",                       "Assyrian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Asturian",                       "Asturian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Australian",                     "Australian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Austrian",                       "Austrian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Azerbaijani",                    "Azerbaijani",                    "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Aztec",                          "Aztec",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bahraini",                       "Bahraini",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Balkan",                         "Balkan",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Balochi",                        "Balochi",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bangladeshi",                    "Bangladeshi",                    "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Basque",                         "Basque",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Belarusian",                     "Belarusian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Belgian",                        "Belgian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Belizean",                       "Belizean",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bengal",                         "Bengal",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Beninese",                       "Beninese",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Berber",                         "Berber",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bhutanese",                      "Bhutanese",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bolivian",                       "Bolivian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bosnia and Herzegovina",         "Bosnia and Herzegovina",         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Botswanan",                      "Botswanan",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Brazilian",                      "Brazilian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("British",                        "British",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bruneian",                       "Bruneian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Buddhist",                       "Buddhist",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bukharan",                       "Bukharan",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Bulgarian",                      "Bulgarian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Burkinabé",                      "Burkinabé",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Burmese",                        "Burmese",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Byzantine",                      "Byzantine",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Cajun",                          "Cajun",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Cambodian",                      "Cambodian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Cameroonian",                    "Cameroonian",                    "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Canadian",                       "Canadian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Caribbean",                      "Caribbean",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Catalan",                        "Catalan",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Caucasian",                      "Caucasian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Central Asian",                  "Central Asian",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Chadian",                        "Chadian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Chilean",                        "Chilean",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Chinese",                        "Chinese",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Circassian",                     "Circassian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Colombian",                      "Colombian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Congolese",                      "Congolese",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Cornish",                        "Cornish",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Creole",                         "Creole",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Crimean",                        "Crimean",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Croatian",                       "Croatian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Cuban",                          "Cuban",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Cypriot",                        "Cypriot",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Czech",                          "Czech",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Danish",                         "Danish",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Djiboutian",                     "Djiboutian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Dutch",                          "Dutch",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Early modern European",          "Early modern European",          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("East African",                   "East African",                   "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ecuadorian",                     "Ecuadorian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Egyptian",                       "Egyptian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Emirati",                        "Emirati",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("English",                        "English",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Equatorial",                     "Equatorial",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Eritrean",                       "Eritrean",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Estonian",                       "Estonian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ethiopian",                      "Ethiopian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("European",                       "European",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Filipino",                       "Filipino",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Finnish",                        "Finnish",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("French",                         "French",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Galician",                       "Galician",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Georgian",                       "Georgian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("German",                         "German",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ghanaian",                       "Ghanaian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Global",                         "Global",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Greek",                          "Greek",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Guatemalan",                     "Guatemalan",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Guinean",                        "Guinean",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Haitian",                        "Haitian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Historical Chinese",             "Historical Chinese",             "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Historical South Asian",         "Historical South Asian",         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Honduran",                       "Honduran",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Hong Kong",                      "Hong Kong",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Hungarian",                      "Hungarian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Icelandic",                      "Icelandic",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Inca",                           "Inca",                           "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Indian",                         "Indian",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Indonesian",                     "Indonesian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Inuit",                          "Inuit",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Iranian",                        "Iranian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Iraqi",                          "Iraqi",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Irish",                          "Irish",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Islamic",                        "Islamic",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Israeli",                        "Israeli",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Italian",                        "Italian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ivorian",                        "Ivorian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Jamaican",                       "Jamaican",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Japanese",                       "Japanese",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Jewish",                         "Jewish",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Jordanian",                      "Jordanian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Kazakh",                         "Kazakh",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Kenyan",                         "Kenyan",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Korean",                         "Korean",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Kosovan",                        "Kosovan",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Kurdish",                        "Kurdish",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Kuwaiti",                        "Kuwaiti",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Kyrgyz",                         "Kyrgyz",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Lao",                            "Lao",                            "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Latin American",                 "Latin American",                 "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Latvian",                        "Latvian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Lebanese",                       "Lebanese",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Levantine",                      "Levantine",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Libyan",                         "Levantine",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Libyan",                         "Libyan",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Liechtensteiner",                "Liechtensteiner",                "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Lithuanian",                     "Lithuanian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Louisiana",                      "Louisiana",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Luxembourg",                     "Luxembourg",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Macau",                          "Macau",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Macedonian",                     "Macedonian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Maharashtrian",                  "Maharashtrian",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Malagasy",                       "Malagasy",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Malaysian",                      "Malaysian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Maltese",                        "Maltese",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Mayan",                          "Mayan",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Medieval",                       "Medieval",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Mediterranean",                  "Mediterranean",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Mexican",                        "Mexican",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Middle Eastern",                 "Middle Eastern",                 "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Mizrahi",                        "Mizrahi",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Moldovan",                       "Moldovan",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Mongolian",                      "Mongolian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Mordovian",                      "Mordovian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Moroccan",                       "Moroccan",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Native",                         "Native",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Nepalese",                       "Nepalese",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("New American",                   "New American",                   "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("New Zealand",                    "New Zealand",                    "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Nigerian",                       "Nigerian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Nigerien",                       "Nigerien",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("North African",                  "North African",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Norwegian",                      "Norwegian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Occitan",                        "Occitan",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Omani",                          "Omani",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ottoman",                        "Ottoman",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Pacific Aisle",                  "Pacific Aisle",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Pakistani",                      "Pakistani",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Palestinian",                    "Palestinian",                    "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Panamanian",                     "Panamanian",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Parsi",                          "Parsi",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Pashtu,n Pennsylvania",          "Pashtu,n Pennsylvania",          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Peasant",                        "Peasant",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Peranakan",                      "Peranakan",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Peruvian",                       "Peruvian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Polish",                         "Polish",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Portuguese",                     "Portuguese",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Punjabi",                        "Punjabi",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Qatari",                         "Qatari",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Romanian",                       "Romanian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Russian",                        "Russian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Salvadoran",                     "Salvadoran",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Sami",                           "Sami",                           "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Saudi",                          "Saudi",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Scottish",                       "Scottish",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Sephardic",                      "Sephardic",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Serbian",                        "Serbian",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Sicilian",                       "Sicilian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Sindhi",                         "Sindhi",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Singaporean",                    "Singaporean",                    "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Slovak",                         "Slovak",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Slovenian",                      "Slovenian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Somali",                         "Somali",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("South African",                  "South African",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Soviet",                         "Soviet",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Spanish",                        "Spanish",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Sri Lankan",                     "Sri Lankan",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Sudanese",                       "Sudanese",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Swazi",                          "Swazi",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Swedish",                        "Swedish",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Swiss",                          "Swiss",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Syrian",                         "Syrian",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Taiwanese",                      "Taiwanese",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Tajik",                          "Tajik",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Tatar",                          "Tatar",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Thai",                           "Thai",                           "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Tibetan",                        "Tibetan",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Trinidadian and Tobagonian",     "Trinidadian and Tobagonian",     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Tunisian",                       "Tunisian",                       "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Turkish",                        "Turkish",                        "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Ukrainian",                      "Ukrainian",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("United States",                  "United States",                  "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Uruguayan",                      "Uruguayan",                      "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Uzbek",                          "Uzbek",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Venezuelan",                     "Venezuelan",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Vietnamese",                     "Vietnamese",                     "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("West African",                   "West African",                   "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Welsh",                          "Welsh",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Yamal",                          "Yamal",                          "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    seeds.append(("Yemeni",                         "Yemeni",                         "",     "en_US",      App.Config.dataVersion.value,     "",     0,      true,     false))
    return seeds
  }
}
